# fly.toml file generated for twilight-paper-8909 on 2023-04-17T16:30:52+03:00

app = "twilight-paper-8909"
primary_region = "jnb"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
